[package]
name = "rustv"
version = "0.1.0"
authors = ["dobkeratops <dobkeratopsgit@gmail.com>"]

[dependencies]
image = "0.18.0"
itertools = "0.7.4"
half = "1.0.1"
array3d = "0.1.0"
vecgenericindex = "0.1.0"
lininterp = "0.1.3"
